### ISSUE TITLE
MultiOgar-Edited does not work with Ubuntu 16.04 LTS!

### ISSUE THREAD

**Issue by Tkuro** [Megabyte918/MultiOgar-Edited#1444]
It does not work on Ubuntu 16.04 LTS.

I do not care much about Node.js so put a log.

I think that it may not work with linux in general.

> [FATAL] TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/home/user/server/self/node_modules/ws/lib/constants.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/server/self/node_modules/ws/lib/permessage-deflate.js:7:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

I'm Japanese.
I am using Google translation because I am not familiar with English very much.

**Comment by MiraMiPalo** [comment]
la dvd no c bro, yo siempre he usado windors xp

**Comment by Tetratrix** [comment]
mira bro la conchingua arikato jmkamfe ajito con ajio ajio :v

**Comment by Luka967** [comment]
You're using an old version of node.js, update to version 7 or later.

**Comment by Tkuro** [comment]
OK, thank you <3
